<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.14" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.14" />
    <PackageReference Include="Npgsql" Version="9.0.4" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
    <PackageReference Include="Resend" Version="0.5.1" />
    <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\CommonService\CommonService.csproj" />
    <ProjectReference Include="..\NotificationsMicroservice.Core\NotificationsMicroservice.Core.csproj" />
  </ItemGroup>

</Project>
