{
 "title": "ASP.NET OTEL Metrics",
 "description": "Shows ASP.NET metrics from OpenTelemetry NuGet",
 "tags": [
  "dotnet",
  "opentelemetry",
  "otel",
  "prometheus",
  "process",
  "runtime",
  "httpclient",
  "aspnetcore"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(dotnet_gc_collections_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(dotnet_gc_collections_total{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "server_address",
    "label": "HTTP Client Pear Name",
    "query": {
     "query": "label_values(http_client_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\",server_address!=\"otel-collector\"},server_address)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System Heath",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Start Time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "product_api_start_time_seconds{job=\"$job\",instance=\"$instance\"}* 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Warmup Time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "product_api_warmup_duration_seconds{job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "Total Time"
      }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(process_cpu_time_seconds_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{process_cpu_state}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max_over_time(process_memory_usage_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Memory Usage"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "stat",
     "gridPos": { "h": 9, "w": 3, "x": 21, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(process_thread_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Threads"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "General Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max_over_time(dotnet_gc_last_collection_memory_committed_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Committed Memory Size"
      },
      {
       "expr": "max_over_time(\r\n  sum(dotnet_gc_last_collection_heap_size_bytes{job=\"$job\", instance=\"$instance\"}) by (job)\r\n  [$__rate_interval:]\r\n)\r\n",
       "legendFormat": "Object Size"
      },
      {
       "expr": "irate(dotnet_gc_heap_allocated_bytes_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Allocations Size"
      }
     ]
    },
    {
     "title": "Heap Generations (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max_over_time(dotnet_gc_last_collection_heap_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{gc_heap_generation}}"
      }
     ]
    },
    {
     "title": "Heap Fragmentation (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max_over_time(dotnet_gc_last_collection_heap_fragmentation_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{gc_heap_generation}}"
      }
     ]
    },
    {
     "title": "GC Collections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (gc_heap_generation) (\r\n  increase(dotnet_gc_collections_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])\r\n)",
       "legendFormat": "{{gc_heap_generation}}"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(dotnet_exceptions_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Exceptions"
      }
     ]
    },
    {
     "title": "ThreadPool Threads",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(dotnet_thread_pool_thread_count_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "ThreadPool Threads"
      }
     ]
    },
    {
     "title": "ThreadPool Threads Queue Length",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(dotnet_thread_pool_queue_length_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "ThreadPool Threads Queue Length"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Responses Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p98"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99.9"
      }
     ]
    },
    {
     "title": "Errors Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_response_status_code!~\"2..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "All"
      },
      {
       "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "4XX"
      },
      {
       "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "5XX"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Client -${server_address}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "server_address",
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", server_address=\"$server_address\"}[$__rate_interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", server_address=\"$server_address\"}[$__rate_interval])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", server_address=\"$server_address\"}[$__rate_interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", server_address=\"$server_address\"}[$__rate_interval])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.98, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", server_address=\"$server_address\"}[$__rate_interval])) by (le))",
       "legendFormat": "p98"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", server_address=\"$server_address\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(http_client_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", server_address=\"$server_address\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99.9"
      }
     ]
    },
    {
     "title": "Errors Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_response_status_code!~\"2..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_client_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))\r\n",
       "legendFormat": "All"
      },
      {
       "expr": "(sum(rate(http_client_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"4..\"}[$__rate_interval])) or vector(0)) / (sum(rate(http_client_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))\r\n",
       "legendFormat": "4XX"
      },
      {
       "expr": "(sum(rate(http_client_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"5..\"}[$__rate_interval])) or vector(0)) / (sum(rate(http_client_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))\r\n",
       "legendFormat": "5XX"
      },
      {
       "expr": "(sum(rate(http_client_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", server_address!=\"otel-collector\", error_type=~\".+\"}[$__rate_interval])) or vector(0)) / (sum(rate(http_client_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", server_address!=\"otel-collector\"}[$__rate_interval])))\r\n",
       "legendFormat": "Connection Error"
      }
     ]
    }
   ]
  },
  {
   "title": "Business Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Products Count",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(current_products{job=\"$job\"})",
       "legendFormat": "{{Total Products}}"
      }
     ]
    },
    {
     "title": "Add Product",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (rate(product_add_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by (le) (rate(product_add_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(product_add_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(product_add_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.98, sum by (le) (rate(product_add_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p98"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(product_add_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Delete Product",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (rate(product_delete_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by (le) (rate(product_delete_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(product_delete_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(product_delete_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.98, sum by (le) (rate(product_delete_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p98"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(product_delete_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Get Product By ProductId",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (rate(product_get_product_by_productId_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by (le) (rate(product_get_product_by_productId_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(product_get_product_by_productId_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(product_get_product_by_productId_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.98, sum by (le) (rate(product_get_product_by_productId_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p98"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(product_get_product_by_productId_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Get All Products",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (rate(product_get_products_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by (le) (rate(product_get_products_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(product_get_products_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(product_get_products_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.98, sum by (le) (rate(product_get_products_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p98"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(product_get_products_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Update Product",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (rate(product_update_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by (le) (rate(product_update_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(product_update_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(product_update_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.98, sum by (le) (rate(product_update_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p98"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(product_update_product_latency_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  }
 ]
}